{"name": "test_input[field_data_dict0]", "status": "broken", "statusDetails": {"message": "TypeError: ContactForm.input_field() takes 2 positional arguments but 4 were given", "trace": "field_data_dict = {'name': 'warvictimsfund'}\n\n    @pytest.mark.parametrize(\"field_data_dict\", [{\"name\": \"warvictimsfund\"}])\n    def test_input(field_data_dict):\n        contact_page = ContactForm(driver)\n>       contact_page.input_field(driver, \"Your Name*\",field_data_dict)\nE       TypeError: ContactForm.input_field() takes 2 positional arguments but 4 were given\n\ntests\\test_contact_form.py:27: TypeError"}, "parameters": [{"name": "field_data_dict", "value": "{'name': 'warvictimsfund'}"}], "start": 1708227084606, "stop": 1708227084606, "uuid": "790f399b-4e8e-4a0c-8f8a-63fa176e8b93", "historyId": "e00ed689311b489d1b37dfae345653e7", "testCaseId": "938ec7942806b96867ac01ccf953ed7f", "fullName": "tests.test_contact_form#test_input", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_contact_form"}, {"name": "host", "value": "udav_comp"}, {"name": "thread", "value": "9988-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_contact_form"}]}